import { auth } from "@/auth";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { Toaster } from "sonner";
import AppSidebar from "../components/AppSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  if (!session?.user) redirect("/");
  return (
    <SidebarProvider>
      <Toaster position="bottom-right" />
      <AppSidebar />
      <main className="w-full relative p-2">
        <SidebarTrigger className="cursor-pointer absolute bottom-0" />
        {children}
      </main>
    </SidebarProvider>
  );
}
