import { auth } from "@/auth";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { Toaster } from "sonner";
import AppSidebar from "../components/AppSidebar";
import SidebarTriggerPlus from "../components/SidebarTriggerPlus";

export const metadata: Metadata = {
  title: {
    template: "%s | Finance",
    default: "Finance Dashboard",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  if (!session?.user) redirect("/");
  return (
    <SidebarProvider>
      <Toaster position="bottom-right" />
      <AppSidebar />
      <main className="w-full relative p-2">
        <SidebarTriggerPlus />
        {children}
      </main>
    </SidebarProvider>
  );
}
