import { auth } from "@/auth";
import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  if (session?.user) redirect("/home");
  return (
    <>
      <Toaster position="bottom-right" />
      {children}
    </>
  );
}
